[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/", "@aragon/osx/=lib/osx/packages/contracts/src/"]
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
sepolia = "${EVM_RPC_URL}"                 # HTTPS RPC for Sepolia
arbitrum_sepolia = "${ARBITRUM_RPC_URL}" # optional

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" } # optional

[profile.default.env]
CHAIN_ID = "${CHAIN_ID}"
DAO_ADDRESS = "${DAO_ADDRESS}"
