[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
evm_version = "paris"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${RPC_URL}"                 # HTTPS RPC for Sepolia
arbitrum_sepolia = "${ARBITRUM_RPC_URL}" # optional

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" } # optional

[profile.default.env]
CHAIN_ID = "${CHAIN_ID}"
DAO_ADDRESS = "${DAO_ADDRESS}"
